import { writeFileSync } from "fs";
import chalk from "chalk";
import { join } from "path";

import { ISerializedGast } from "chevrotain";

/**
 * Script to generate the serialized grammar.
 *
 * This is to avoid minification issues when rhombic is used in production mode.
 *
 * Ref: https://github.com/SAP/chevrotain/blob/master/examples/parser/minification/README.md
 *
 * Result:
 *   `src/serializedGrammar.ts`
 */
export function generateSerializedGrammar(grammar: ISerializedGast[]) {
  const output = `// Auto-generated by generateSerialedGrammar.ts

export const serializedGrammar = ${JSON.stringify(grammar, null, 2)};`;
  writeFileSync(join(__dirname, "../serializedGrammar.ts"), output);
  console.log(chalk.green("✔") + " serialized grammar generated!");
}
