export default {
    ENABLE_DARK_THEME: 'ENABLE_DARK_THEME',
    INIT_APP: 'INIT_APP',
    SET_USER_CONNECTION: 'SET_USER_CONNECTION',
    USER_AUTHORIZED: 'USER_AUTHORIZED',
    USER_LOGOUT: 'LOGOUT',
    LOAD_STRUCETURE: 'LOAD_STRUCTURE',
    EXPAND_STRUCTURE: 'EXPAND_STRUCTURE'
};
