export default {
    CHANGE_MODE: 'CHANGE_MODE',
    LOAD_CONNECTIONS: 'LOAD_CONNECTIONS',
    UPDATE_CONNECTION: 'UPDATE_CONNECTION',
    DISABLE_ACTIVE_CONNECTIONS: 'DISABLE_ACTIVE_CONNECTIONS',
    NEW_CONNECTION: 'NEW_CONNECTION',
    ACTIVATE_CONNECTION: 'ACTIVATE_CONNECTION',
    PUSH_CONNECTION: 'PUSH_CONNECTION',
    LOGIN_REQUEST: 'REQUEST_LOGIN',
    LOGIN_COMPLETE: 'LOGIN_COMPLETE',
    LOGIN_ERROR: 'LOGIN_ERROR'
};
