export default {
    CHANGE_MODE: 'CHANGE_MODE',
    LOAD_CONNECTIONS: 'LOAD_CONNECTIONS',
    UPDATE_CONNECTION: 'UPDATE_CONNECTION',
    DISABLE_ACTIVE_CONNECTIONS: 'DISABLE_ACTIVE_CONNECTIONS',
    NEW_CONNECTION: 'NEW_CONNECTION',
    ACTIVATE_CONNECTION: 'ACTIVATE_CONNECTION'
};
